// Vertex gRPC transport wire protocol.
//
// Vertex's 4-frame envelope (see /spec/wire-format.md §2) is transported over
// gRPC bidi streams by splitting each envelope into 4 consecutive TransportFrame
// messages, with end_of_message = true on the 4th.
//
// Business payloads (the contents of TransportFrame.payload at the 4th frame
// position) are serialized using Protobuf at this transport, not MessagePack
// or anything else — gRPC's whole point is Protobuf tooling.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.3
// source: vertex/transport/grpc/v1/bidi.proto

// Proto package includes the version; the directory path already lives under
// /transport/grpc/v1/, so we don't duplicate the version here either.

package protocolv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransportFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Opaque bytes of one envelope frame.
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// true on the 4th (last) frame of each Vertex envelope.
	// Receiver accumulates frames until end_of_message, then hands the
	// 4-frame envelope to the messaging layer.
	EndOfMessage  bool `protobuf:"varint,2,opt,name=end_of_message,json=endOfMessage,proto3" json:"end_of_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportFrame) Reset() {
	*x = TransportFrame{}
	mi := &file_vertex_transport_grpc_v1_bidi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportFrame) ProtoMessage() {}

func (x *TransportFrame) ProtoReflect() protoreflect.Message {
	mi := &file_vertex_transport_grpc_v1_bidi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportFrame.ProtoReflect.Descriptor instead.
func (*TransportFrame) Descriptor() ([]byte, []int) {
	return file_vertex_transport_grpc_v1_bidi_proto_rawDescGZIP(), []int{0}
}

func (x *TransportFrame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TransportFrame) GetEndOfMessage() bool {
	if x != nil {
		return x.EndOfMessage
	}
	return false
}

var File_vertex_transport_grpc_v1_bidi_proto protoreflect.FileDescriptor

const file_vertex_transport_grpc_v1_bidi_proto_rawDesc = "" +
	"\n" +
	"#vertex/transport/grpc/v1/bidi.proto\x12\x18vertex.transport.grpc.v1\"P\n" +
	"\x0eTransportFrame\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12$\n" +
	"\x0eend_of_message\x18\x02 \x01(\bR\fendOfMessage2i\n" +
	"\x04Bidi\x12a\n" +
	"\aConnect\x12(.vertex.transport.grpc.v1.TransportFrame\x1a(.vertex.transport.grpc.v1.TransportFrame(\x010\x01BiZCgithub.com/dengxuan/vertex-go/transport/grpc/protocol/v1;protocolv1\xaa\x02!Vertex.Transport.Grpc.Protocol.V1b\x06proto3"

var (
	file_vertex_transport_grpc_v1_bidi_proto_rawDescOnce sync.Once
	file_vertex_transport_grpc_v1_bidi_proto_rawDescData []byte
)

func file_vertex_transport_grpc_v1_bidi_proto_rawDescGZIP() []byte {
	file_vertex_transport_grpc_v1_bidi_proto_rawDescOnce.Do(func() {
		file_vertex_transport_grpc_v1_bidi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vertex_transport_grpc_v1_bidi_proto_rawDesc), len(file_vertex_transport_grpc_v1_bidi_proto_rawDesc)))
	})
	return file_vertex_transport_grpc_v1_bidi_proto_rawDescData
}

var file_vertex_transport_grpc_v1_bidi_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vertex_transport_grpc_v1_bidi_proto_goTypes = []any{
	(*TransportFrame)(nil), // 0: vertex.transport.grpc.v1.TransportFrame
}
var file_vertex_transport_grpc_v1_bidi_proto_depIdxs = []int32{
	0, // 0: vertex.transport.grpc.v1.Bidi.Connect:input_type -> vertex.transport.grpc.v1.TransportFrame
	0, // 1: vertex.transport.grpc.v1.Bidi.Connect:output_type -> vertex.transport.grpc.v1.TransportFrame
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vertex_transport_grpc_v1_bidi_proto_init() }
func file_vertex_transport_grpc_v1_bidi_proto_init() {
	if File_vertex_transport_grpc_v1_bidi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vertex_transport_grpc_v1_bidi_proto_rawDesc), len(file_vertex_transport_grpc_v1_bidi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vertex_transport_grpc_v1_bidi_proto_goTypes,
		DependencyIndexes: file_vertex_transport_grpc_v1_bidi_proto_depIdxs,
		MessageInfos:      file_vertex_transport_grpc_v1_bidi_proto_msgTypes,
	}.Build()
	File_vertex_transport_grpc_v1_bidi_proto = out.File
	file_vertex_transport_grpc_v1_bidi_proto_goTypes = nil
	file_vertex_transport_grpc_v1_bidi_proto_depIdxs = nil
}
