// Vertex gRPC transport wire protocol.
//
// Vertex's 4-frame envelope (see /spec/wire-format.md §2) is transported over
// gRPC bidi streams by splitting each envelope into 4 consecutive TransportFrame
// messages, with end_of_message = true on the 4th.
//
// Business payloads (the contents of TransportFrame.payload at the 4th frame
// position) are serialized using Protobuf at this transport, not MessagePack
// or anything else — gRPC's whole point is Protobuf tooling.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.3
// source: vertex/v1/transport/grpc/v1/bidi.proto

package protocolv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bidi_Connect_FullMethodName = "/vertex.v1.transport.grpc.v1.Bidi/Connect"
)

// BidiClient is the client API for Bidi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BidiClient interface {
	// Single bidirectional stream. Client connects once and exchanges an
	// unbounded interleaving of events / requests / responses.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransportFrame, TransportFrame], error)
}

type bidiClient struct {
	cc grpc.ClientConnInterface
}

func NewBidiClient(cc grpc.ClientConnInterface) BidiClient {
	return &bidiClient{cc}
}

func (c *bidiClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TransportFrame, TransportFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bidi_ServiceDesc.Streams[0], Bidi_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransportFrame, TransportFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bidi_ConnectClient = grpc.BidiStreamingClient[TransportFrame, TransportFrame]

// BidiServer is the server API for Bidi service.
// All implementations must embed UnimplementedBidiServer
// for forward compatibility.
type BidiServer interface {
	// Single bidirectional stream. Client connects once and exchanges an
	// unbounded interleaving of events / requests / responses.
	Connect(grpc.BidiStreamingServer[TransportFrame, TransportFrame]) error
	mustEmbedUnimplementedBidiServer()
}

// UnimplementedBidiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBidiServer struct{}

func (UnimplementedBidiServer) Connect(grpc.BidiStreamingServer[TransportFrame, TransportFrame]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedBidiServer) mustEmbedUnimplementedBidiServer() {}
func (UnimplementedBidiServer) testEmbeddedByValue()              {}

// UnsafeBidiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BidiServer will
// result in compilation errors.
type UnsafeBidiServer interface {
	mustEmbedUnimplementedBidiServer()
}

func RegisterBidiServer(s grpc.ServiceRegistrar, srv BidiServer) {
	// If the following call panics, it indicates UnimplementedBidiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bidi_ServiceDesc, srv)
}

func _Bidi_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BidiServer).Connect(&grpc.GenericServerStream[TransportFrame, TransportFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bidi_ConnectServer = grpc.BidiStreamingServer[TransportFrame, TransportFrame]

// Bidi_ServiceDesc is the grpc.ServiceDesc for Bidi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bidi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vertex.v1.transport.grpc.v1.Bidi",
	HandlerType: (*BidiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Bidi_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "vertex/v1/transport/grpc/v1/bidi.proto",
}
